version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/codebase
hooks:
  BeforeInstall:
    - location: /home/ec2-user/codebase/scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: /home/ec2-user/codebase/scripts/change_permissions.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: /home/ec2-user/codebase/scripts/application_start.sh
    - location: /home/ec2-user/codebase/scripts/create_test_db.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: /home/ec2-user/codebase/scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
