version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/codebase
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: change_permissions.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: application_start.sh
    - location: scripts/create_test_db.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: application_stop.sh
      timeout: 300
      runas: ec2-user
